### ISSUE TITLE
<OkendoProvider /> attempting to access `window` in App.server.jsx/tsx

### ISSUE THREAD

**Issue by cnr-mtsn** [okendo/okendo-shopify-hydrogen-demo#11]
The Provider appears to be reaching for the window object server-side - in App.server.jsx/tsx - which is causing a build error. Thus, this package only works in development.

**Comment by susannepeng** [comment]
Hi @cnr-mtsn, I'm unable to reproduce this error in our [latest release (v.1.2.0)](https://github.com/okendo/okendo-shopify-hydrogen-demo/releases/tag/v1.2.0).

Would you mind providing some more information so we can look into this?

- the version of the package you are on
- the build error output
- how you are preparing your application for production

**Comment by cnr-mtsn** [comment]
<img width="382" alt="image" src="https://user-images.githubusercontent.com/46786879/183717010-138a59a9-269b-439f-90eb-942bea574673.png">

Build Error output: [here](https://pipelines.actions.githubusercontent.com/serviceHosts/6949aabd-7513-4add-a025-a6a8e796f758/_apis/pipelines/1/runs/69/signedlogcontent/2?urlExpires=2022-08-09T17%3A24%3A01.1761338Z&urlSigningMethod=HMACV1&urlSignature=cZ2FkBmwVNaMgDM22WEXfcxqovz%2BUPuL18QcNRPnGBA%3D)

deploying to Oxygen

moes-test-plus-store.myshopify.com

**Comment by owlyowl** [comment]
Hi Connor,
We've managed to work around the issue.

Looks like react-html-parser references the window object so we've had to
remove that from the OkendoProvider.

We'll have a new release up shortly.

**Comment by cnr-mtsn** [comment]
Awesome! 😀
