### ISSUE TITLE
Updates required for Hydrogen 2

### ISSUE THREAD

**Issue by razza12** [okendo/okendo-shopify-hydrogen-demo#21]
Now that Hydrogen 2 is the default entrypoint - will the packages be updated for compatibility with new Remix data fetching (currently getting several import errors as below)

` ✘ [ERROR] No matching export in "node_modules/@shopify/hydrogen/dist/production/index.js" for import "gql"

    node_modules/@okendo/shopify-hydrogen/dist/esnext/fragments/index.js:1:9:
      1 │ import { gql } from '@shopify/hydrogen';
        ╵          ~~~

 ✘ [ERROR] No matching export in "node_modules/@shopify/hydrogen/dist/production/index.js" for import "useRequestContext"

    node_modules/@okendo/shopify-hydrogen/dist/esnext/shared/server/requestUtils.js:1:9:
      1 │ import { useRequestContext } from '@shopify/hydrogen';`

**Comment by tomokendo** [comment]
Thanks for reaching out Ryan.
We're in the process of moving towards Hydrogen 2.

I would suggest you reach out to our sales team at sales@okendo.io and mention you have a Hydrogen 2 requirement and we'll keep you posted.

**Comment by dcodrin** [comment]
@tomokendo We are planning to go live with hydrogen v2 in April and unfortunately we are considering an alternative provider since okendo is no longer compatible, do you have any timelines by any chance as we might wait if it's reasonable. Thank you!

**Comment by tomokendo** [comment]
> @tomokendo We are planning to go live with hydrogen v2 in April and unfortunately we are considering an alternative provider since okendo is no longer compatible, do you have any timelines by any chance as we might wait if it's reasonable. Thank you!

Hi @dcodrin  - I was wondering which merchant you are currently working with please?

**Comment by dcodrin** [comment]
@tomokendo We actually signed up with okendo. We built a store using v1 of hydrogen, but decided to migrate to v2 before launching since it's much easier and faster rather than launching with v1 and then migrating to v2. The implementation worked great with v1 save for one small issue where the base styles were overwritten by the custom styles upon load. Would be really great to get a v2 version since not a lot of solutions out there offer this type of native integration.

**Comment by dylanmcgowan** [comment]
How is the hydrogen 2 integration coming along?

**Comment by tomokendo** [comment]
Hi Dylan,
We plan to have something out early May at this stage.

**Comment by Zwyx** [comment]
Hi @razza12, @dcodrin, @dylanmcgowan, I'm pleased to announce that we have published the Okendo Hydrogen 2 Components!

You will find the library and its documentation at https://www.npmjs.com/package/@okendo/shopify-hydrogen.

The [demo store](https://github.com/okendo/okendo-shopify-hydrogen-demo) in this repo has also been updated.

Please feel free to contact us should you have any question or feedback.

**Comment by owlyowl** [comment]
Hi Dylan,
It would appear you're using our Widget version 1 offering.
The metafield you mention is the v1 metafield.

We released a new version of our Widgets last year called Widget Plus.

Our Hydrogen libraries are designed to work with Widget Plus not v1 of our widgets.

I'd encourage you to upgrade your store to Widget Plus (it's free to upgrade) by contacting support@okendo.io and we can get you sorted out.

Thanks,
Tom
