### ISSUE TITLE
Stackblitz Template Example is unavailable or broken

### ISSUE THREAD

**Issue by waynemorphic** [okendo/okendo-shopify-hydrogen-demo#22]
![Screenshot from 2023-04-04 11-16-50](https://user-images.githubusercontent.com/37283450/229731366-a5f3951c-7d94-4028-b096-64987ed1f641.png)

**Comment by waynemorphic** [comment]
Hi @Zwyx thank you for your feedback. To run the attached Shopify demo templates, users need a premium Stackblitz account.

Curious to know if Okendo's widgets are open source and if they are, how can I contribute to their development and adaption?

**Comment by Zwyx** [comment]
Thanks for your interest! However Okendo's widgets aren't open source at the moment.
