### ISSUE TITLE
Review widget returns empty when redirected to another pages

### ISSUE THREAD

**Issue by tuanfront-end** [okendo/okendo-shopify-hydrogen-demo#28]
Thanks for this great project, however I'm having this problem:
Product A has been reviewed, but when accessed, sometimes the review is displayed, and sometimes the review widget returns empty.
Please check it here - https://ciseco-hydrogen-vite-56385ad898867bbff28c.o2.myshopify.dev/products/blue-silk-tuxedo?Color=Pink&Size=Small
Hope to receive a response from you soon.

**Comment by tuanfront-end** [comment]
Expectation: When product A has review data, when accessing the product, the review widget will always display the correct data.

**Comment by Zwyx** [comment]
Hi @tuanfront-end, thank you for reaching out to us. It looks like SSR isn't working on your page. This could happens if you haven't installed the metafields, or granted storefront access to them. You can read more at https://www.npmjs.com/package/@okendo/shopify-hydrogen

**Comment by owlyowl** [comment]
If you wouldn't mind sharing read-only access to your source we're happy to take a look ASAP.
Please reach out to tom.fulcher@okendo.io

**Comment by tuanfront-end** [comment]
Hi @Zwyx  @owlyowl , thank you very much for your feedback, I honestly missed the step of initializing the metafields. I will check them again and will let you know the results

**Comment by tuanfront-end** [comment]
Hey @Zwyx , sorry I'm not really familiar with these things, but is my approach correct?
<img width="1914" alt="Screenshot 2024-04-29 at 08 43 01" src="https://github.com/okendo/okendo-shopify-hydrogen-demo/assets/19155701/6a2ef109-4595-423e-9eea-0de0205e218f">

**Comment by tuanfront-end** [comment]
When I tried to check more closely on the admin page, it seemed like the metaobjects were automatically defined

<img width="1075" alt="Screenshot 2024-04-29 at 10 48 01" src="https://github.com/okendo/okendo-shopify-hydrogen-demo/assets/19155701/72edc7ba-a2a6-4955-ab59-34a905da23c6">

**Comment by owlyowl** [comment]
Just because the metafields are there without definition does not mean they have been exposed via the Storefront API.

Please reach out to me tom.fulcher@okendo.io and if you wouldn't mind giving me collaborator access we can help with the expose and install. I'd be happy to double check your Hydrogen repo if you wanted to give us read access as well.

**Comment by tuanfront-end** [comment]
Thank you so much @owlyowl, I have sent you an email, please check it and I am happy to share my Hydrogen project and hope you can help.

**Comment by tomokendo** [comment]
Now resolved. Client needed to correctly expose metafields as per NPM documentation.
