### ISSUE TITLE
Prop `nonce` did not match. Server: "****" Client: "" Error Component Stack

### ISSUE THREAD

**Issue by octave** [okendo/okendo-shopify-hydrogen-demo#34]
I'm currently using `@okendo/shopify-hydrogen@2.2.5` with the latest `@shopify/hydrogen@2024.10.0`. it is working but it's throwing a warning error in the browser: `Prop 'nonce' did not match. Server: "0f59db05b92ee6ad129dc9ac011cccb1" Client: "" Error Component Stack`

This is my code where you can see that the `nonce` is passed:

```javascript
          <OkendoProvider
            nonce={nonce}
            okendoProviderData={data.okendoProviderData}
          >
            <Analytics.Provider
              cart={data.cart}
              shop={data.shop}
              consent={data.consent}
            >
              <PageLayout {...data}>{children}</PageLayout>
            </Analytics.Provider>
          </OkendoProvider>
```

**Comment by Zwyx** [comment]
Hi Octave, thank you for contacting us. I'm updating our demo store at the moment, and using the exact same versions as you, I cannot reproduce the issue you're having.

Could you please reach out to our support (on [okendo.io](https://okendo.io), use the chat widget at the bottom-right of the page). They'll ask you more details about your project, and if you could give us access to your repo, or at least part of the source code, they'll be able to assist rapidly.

**Comment by octave** [comment]
Hi @Zwyx, thank you, will do! Just for your info I used the latest hydrogen skeleton and so I adapted the `root.tsx` file to make it as close to yours. Here are the different block with the Okendo integration:

```typescript
import {OkendoProvider, getOkendoProviderData} from '@okendo/shopify-hydrogen';
``` 

```typescript

export async function loader(args: LoaderFunctionArgs) {
  // Start fetching non-critical data without blocking time to first byte
  const deferredData = loadDeferredData(args);

  // Await the critical data required to render initial state of the page
  const criticalData = await loadCriticalData(args);

  const {storefront, env} = args.context;

  return defer({
    ...deferredData,
    ...criticalData,
    publicStoreDomain: env.PUBLIC_STORE_DOMAIN,
    shop: getShopAnalytics({
      storefront,
      publicStorefrontId: env.PUBLIC_STOREFRONT_ID,
    }),
    consent: {
      checkoutDomain: env.PUBLIC_CHECKOUT_DOMAIN,
      storefrontAccessToken: env.PUBLIC_STOREFRONT_API_TOKEN,
      withPrivacyBanner: false,
    },
    okendoProviderData: getOkendoProviderData({
      context: args.context,
      subscriberId: '**********',
    }),
  });
}
``` 

```typescript
export function Layout({children}: {children?: React.ReactNode}) {
  const nonce = useNonce();
  const data = useRouteLoaderData<RootLoader>('root');

  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width,initial-scale=1" />
        <meta
          name="oke:subscriber_id"
          content="**************"
        />
        <Meta />
        <Links />
      </head>
      <body>
        {data ? (
          <OkendoProvider
            nonce={nonce}
            okendoProviderData={data.okendoProviderData}
          >
            <Analytics.Provider
              cart={data.cart}
              shop={data.shop}
              consent={data.consent}
            >
              <PageLayout {...data}>{children}</PageLayout>
            </Analytics.Provider>
          </OkendoProvider>
        ) : (
          children
        )}
        <ScrollRestoration nonce={nonce} />
        <Scripts nonce={nonce} />
      </body>
    </html>
  );
}

export default function App() {
  return <Outlet />;
}
```

**Comment by Zwyx** [comment]
Hi Octave, it seems that we are doing exactly the same thing, but I can't see the nonce error you're having. Feel free to have a look at the [PR I made to update Hydrogen to `2024.10`](https://github.com/okendo/okendo-shopify-hydrogen-demo/pull/35) using Shopify's latest template (the [second commit](https://github.com/okendo/okendo-shopify-hydrogen-demo/pull/35/commits/b7c9dc7129277c4e263bba01d609ac78b7b68af1) especially, where I set up Okendo's widgets).

**Comment by octave** [comment]
@Zwyx Nice! Sorry about that, I realized it was caused by a Chrome extension...
