### ISSUE TITLE
Hide OkendoStarRating until is fully loaded

### ISSUE THREAD

**Issue by octave** [okendo/okendo-shopify-hydrogen-demo#37]
I've noticed that the `OkendoStarRating` component displays without css for a split second at page load. Would there be a way to hide it until it's fully loaded?

**Comment by Zwyx** [comment]
Hi Octave, thanks for reaching out to us again, would you be able to share a link to a page where this issue is happening? If you'd rather not do it publicly, please contact our support using the chat widget on [okendo.io](https://okendo.io/).

**Comment by octave** [comment]
@Zwyx link sent via the chat widget!

**Comment by octave** [comment]
@Zwyx did you receive it?

**Comment by Zwyx** [comment]
Yes we did, sorry we didn't acknowledge it, we are investigating your issue at the moment.

**Comment by octave** [comment]
You might not see the problem as we are not using the `OkendoStarRating` component anymore. We just recreated the component manually using the `summaryData` from the metafields. This we can also fully customize it too.

**Comment by octave** [comment]
Thanks @Zwyx, noted!
